name: karibu_capital_core_crash_reporting
description: Karibu capital crash reporting package.
version: 0.0.1
homepage: none

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  # Flutter plugin for Firebase Crashlytics.
  firebase_crashlytics: ^3.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  karibu_capital_core_static_analysis:
    path: ../static_analysis

  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea
