name: karibu_capital_core_crash_reporting
description: Karibu capital crash reporting package.
version: 0.0.1
homepage: none

environment:
  sdk: "3.0.6"
  flutter: "3.10.6"

dependencies:
  # Flutter plugin for Firebase Crashlytics.
  firebase_crashlytics: ^3.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  karibu_capital_core_static_analysis:
    path: ../static_analysis

  # Static analysis tool that also collects various useful metrics.
  dart_code_metrics: ^4.9.1
