name: karibu_capital_core_remote_config
description: Karibu Capital remote config package.
version: 0.0.1
homepage: none

environment:
  sdk: "3.0.6"
  flutter: "3.10.6"

dependencies:
  flutter:
    sdk: flutter

  # Flutter plugin for Remote Config. Allowing us to change app configurations without
  # releasing new versions of the app. This also allows us to do A/B testing.
  firebase_remote_config: ^3.0.9

  # Package for logging debug and error messages.
  logging: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Common static analysis options.
  karibu_capital_core_static_analysis:
    path: ../static_analysis

  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea
