name: karibu_capital_core_cloud_messaging
description: Karibu Capital messaging package
version: 0.0.1
homepage: none

environment:
  sdk: ^3.3.1

dependencies:
  # Flutter plugin for Firebase Cloud messaging, enabling sending and receiving notification
  # messages.
  firebase_messaging: ^14.2.1

dev_dependencies:
  # Common static analysis options.
  karibu_capital_core_static_analysis:
    path: ../static_analysis

  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea
