name: karibu_capital_core_static_analysis
description: Karibu capital static analysis package.
version: 0.0.1
homepage:

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea
