name: karibu_capital_core_static_analysis
description: Karibu capital static analysis package.
version: 0.0.1
homepage:

environment:
  sdk: ^3.3.1

dependencies:
  # Static analysis tool that also collects various useful metrics.
  dart_code_metrics: ^4.19.2
