name: karibu_capital_core_static_analysis
description: Karibu static analysis package.
version: 0.0.1
homepage:

environment:
  sdk: "2.18.6"
  flutter: "3.3.10"

dependencies:
  # Static analysis tool that also collects various useful metrics.
  dart_code_metrics: ^4.19.2