name: karibu_capital_core_utils
description: Karibu Capital core utility classes for all apps.
version: 0.0.1
homepage: none
publish_to: none

environment:
  sdk: "3.0.6"

dependencies:
  # Provides internationalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting and parsing, and bidirectional text.
  flutter:
    sdk: flutter

  #Provides internationalization and localization facilities, including message translation,
  # plurals and genders, date/number formatting and parsing, and bidirectional text.
  intl: ^0.18.0

  # Wrapper around InheritedWidget, useful for passing states
  # down the widget tree.
  provider: ^6.0.0

  # A composable, Future-based library for making HTTP requests.
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Standard package for unit tests in Dart.
  test: ^1.16.5

  # APIs and utilities for UI testing via screenshots diffing.
  golden_toolkit: ^0.10.0

  # Static analysis tool that also collects various useful metrics.
  dart_code_linter:
    git:
      url: https://github.com/karibu-cap/dart-code-linter.git
      ref: f687f9984d4cff5786aa0173465ba772d8384bea

  karibu_capital_core_static_analysis:
    path: ../static_analysis

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
