name: karibu_capital_core_internationalization
description: Core utility classes for internationalize apps.
version: 0.0.1
homepage:

environment:
   sdk: "3.0.6"
   flutter: "3.10.6"

dependencies:
   path: ^1.8.0

   # Provides internationalization and localization facilities, including message translation,
   # plurals and genders, date/number formatting and parsing, and bidirectional text.
   intl: ^0.18.0

   # Flutter localization dependency.
   flutter_localizations:
      sdk: flutter

   # Package for logging debug and error messages.
   logging: ^1.0.1

dev_dependencies:
   lints: ^1.0.0
   test: ^1.16.0
